### ISSUE TITLE
[Typescript] Convert test files to typescript

### ISSUE THREAD

**Issue by Naturalclar** [phenyl-js/phenyl#200]
## TODO
Convert test files to typescript

## Progress 

🏃- **In Progress**
:eyes: - **Needs Review**
✅ - **Done**
 
- [x] `http-client` (@Naturalclar) 🏃 
- [x] `http-rules` (@nicholaslee119) :eyes:
- [x] `lambda-adapter` (@nicholaslee119) :eyes:
- [x] `memory-db` (@nicholaslee119) 🏃 
- [x] `redux` (@nicholaslee119) :eyes:
- [x] `state` (@Naturalclar) :eyes:

**Comment by Naturalclar** [comment]
I'll work on `http-client`

**Comment by sasurau4** [comment]
done
